version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pensar_db
    restart: always
    environment:
      POSTGRES_USER: pensar_user
      POSTGRES_PASSWORD: pensar_password
      POSTGRES_DB: pensar_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: